### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by mr-tron** [shengdoushi/golang-base58-bench#1]
> shengdoushi/base58 and mr-tron/base58 are both fastest. In terms of encoding methods, they are roughly the same logic. But in decoding, they are not the same. shengdoushi/base58 can use custom alphabet 

It\`s not truth. mr-tron/base58 also can use custom alphabets for decoding since december 2017

**Comment by shengdoushi** [comment]
I said "shengdoushi/base58 can use custom alphabet just like '一二三四五六七八九十壹贰叁肆伍陆柒捌玖零拾佰仟万亿圆甲乙丙丁戊己庚辛壬癸子丑寅卯辰巳午未申酉戌亥金木水火土雷电风雨福'."

not "shengdoushi/base58 can use custom alphabet"

**Comment by shengdoushi** [comment]
update README : https://github.com/shengdoushi/golang-base58-bench/commit/f7e7767608b4029a79a08f5b4282ac0663e13cb8
